// frases.js — Frases del presentador per a cada número de la Quina de Nadal
const FRASES = {
  1:  ["El número u!", "Un! El debut!", "El primer de tots!"],
  2:  ["El dos, parella!", "El dos!", "Dos, dos!"],
  3:  ["El tres, la Trinitat!", "Tres en ratlla!", "El número tres!"],
  4:  ["El quatre, quatre potes!", "Les quatre cantonades!", "El quatre!"],
  5:  ["El cinc, la mà oberta!", "Cinc dits té la mà!", "El número cinc!"],
  6:  ["El sis, el cap per avall!", "Sis, girat és el nou!", "El número sis!"],
  7:  ["El set, la sort!", "Set, porta bona sort!", "El set!"],
  8:  ["El vuit, l'infinit de peu!", "Dos cercles, el vuit!", "El número vuit!"],
  9:  ["El nou, quasi deu!", "El nou!", "Nou!"],
  10: ["El deu, rodó rodó!", "La primera desena!", "El número deu!"],
  11: ["L'onze, les cames d'un flac!", "Onze, dos palitos!", "L'onze!"],
  12: ["Dotze, la dotzena!", "Dotze mesos té l'any!", "El dotze!"],
  13: ["El tretze, la mala sort!", "Tretze, ui que por!", "El tretze, número de bruixes!"],
  14: ["Catorze!", "El número catorze!", "Catorze!"],
  15: ["Quinze!", "El quinze, la meitat i mig!", "Quinze!"],
  16: ["Setze jutges menjant fetge!", "El setze!", "Setze!"],
  17: ["Disset!", "El disset!", "Disset, número de sort!"],
  18: ["Divuit, major d'edat!", "El divuit!", "Divuit!"],
  19: ["El dinou, quasi vint!", "Dinou!", "El dinou!"],
  20: ["El vint, els ulls d'una cara!", "Vint anys, la joventut!", "El número vint!"],
  21: ["Vint-i-u!", "El vint-i-u!", "Vint-i-u!"],
  22: ["Vint-i-dos, dos patets!", "El vint-i-dos!", "Vint-i-dos!"],
  23: ["Vint-i-tres!", "El vint-i-tres!", "Vint-i-tres!"],
  24: ["Vint-i-quatre, Nochebuena!", "El vint-i-quatre!", "Vint-i-quatre!"],
  25: ["El vint-i-cinc, Bon Nadal!", "Vint-i-cinc de desembre!", "Vint-i-cinc, Nadal!"],
  26: ["Vint-i-sis, Sant Esteve!", "El vint-i-sis, carn d'olla!", "Vint-i-sis!"],
  27: ["Vint-i-set!", "El vint-i-set!", "Vint-i-set!"],
  28: ["Vint-i-vuit, Sants Innocents!", "Vint-i-vuit, compte que és Innocents!", "Vint-i-vuit!"],
  29: ["Vint-i-nou!", "El vint-i-nou!", "Vint-i-nou!"],
  30: ["Trenta, la trentena!", "Tres desenes, el trenta!", "El número trenta!"],
  31: ["Trenta-u, l'últim de l'any!", "Cap d'any, el trenta-u!", "Trenta-u!"],
  32: ["Trenta-dos, les dents!", "El trenta-dos!", "Trenta-dos!"],
  33: ["Trenta-tres, l'edat de Crist!", "Trenta-tres, digues!!", "El trenta-tres!"],
  34: ["Trenta-quatre!", "El trenta-quatre!", "Trenta-quatre!"],
  35: ["Trenta-cinc!", "El trenta-cinc!", "Trenta-cinc!"],
  36: ["Trenta-sis!", "El trenta-sis!", "Trenta-sis!"],
  37: ["Trenta-set!", "El trenta-set!", "Trenta-set!"],
  38: ["Trenta-vuit!", "El trenta-vuit!", "Trenta-vuit!"],
  39: ["Trenta-nou!", "El trenta-nou!", "Trenta-nou!"],
  40: ["Quaranta, quaranta dies al desert!", "El quaranta!", "Quaranta!"],
  41: ["Quaranta-u!", "El quaranta-u!", "Quaranta-u!"],
  42: ["Quaranta-dos, la resposta a tot!", "El quaranta-dos!", "Quaranta-dos!"],
  43: ["Quaranta-tres!", "El quaranta-tres!", "Quaranta-tres!"],
  44: ["Quaranta-quatre, doble quatre!", "El quaranta-quatre!", "Quaranta-quatre!"],
  45: ["Quaranta-cinc, meitat de noranta!", "El quaranta-cinc!", "Quaranta-cinc!"],
  46: ["Quaranta-sis!", "El quaranta-sis!", "Quaranta-sis!"],
  47: ["Quaranta-set!", "El quaranta-set!", "Quaranta-set!"],
  48: ["Quaranta-vuit!", "El quaranta-vuit!", "Quaranta-vuit!"],
  49: ["Quaranta-nou!", "El quaranta-nou!", "Quaranta-nou!"],
  50: ["Cinquanta, la meitat!", "Cinquanta, meitat del camí!", "Ja som a la meitat, el cinquanta!"],
  51: ["Cinquanta-u!", "El cinquanta-u!", "Cinquanta-u!"],
  52: ["Cinquanta-dos, les setmanes de l'any!", "El cinquanta-dos!", "Cinquanta-dos!"],
  53: ["Cinquanta-tres!", "El cinquanta-tres!", "Cinquanta-tres!"],
  54: ["Cinquanta-quatre!", "El cinquanta-quatre!", "Cinquanta-quatre!"],
  55: ["Cinquanta-cinc, doble cinc!", "El cinquanta-cinc!", "Cinquanta-cinc!"],
  56: ["Cinquanta-sis!", "El cinquanta-sis!", "Cinquanta-sis!"],
  57: ["Cinquanta-set!", "El cinquanta-set!", "Cinquanta-set!"],
  58: ["Cinquanta-vuit!", "El cinquanta-vuit!", "Cinquanta-vuit!"],
  59: ["Cinquanta-nou!", "El cinquanta-nou!", "Cinquanta-nou!"],
  60: ["Seixanta, l'edat daurada!", "El seixanta!", "Seixanta!"],
  61: ["Seixanta-u!", "El seixanta-u!", "Seixanta-u!"],
  62: ["Seixanta-dos!", "El seixanta-dos!", "Seixanta-dos!"],
  63: ["Seixanta-tres!", "El seixanta-tres!", "Seixanta-tres!"],
  64: ["Seixanta-quatre!", "El seixanta-quatre!", "Seixanta-quatre!"],
  65: ["Seixanta-cinc, edat de jubilació!", "El seixanta-cinc!", "Seixanta-cinc!"],
  66: ["Seixanta-sis!", "El seixanta-sis!", "Seixanta-sis!"],
  67: ["Seixanta-set!", "El seixanta-set!", "Seixanta-set!"],
  68: ["Seixanta-vuit!", "El seixanta-vuit!", "Seixanta-vuit!"],
  69: ["Seixanta-nou!", "El seixanta-nou!", "Seixanta-nou!"],
  70: ["Setanta, l'edat de la saviesa!", "El setanta!", "Setanta!"],
  71: ["Setanta-u!", "El setanta-u!", "Setanta-u!"],
  72: ["Setanta-dos!", "El setanta-dos!", "Setanta-dos!"],
  73: ["Setanta-tres!", "El setanta-tres!", "Setanta-tres!"],
  74: ["Setanta-quatre!", "El setanta-quatre!", "Setanta-quatre!"],
  75: ["Setanta-cinc, tres quarts de cent!", "El setanta-cinc!", "Setanta-cinc!"],
  76: ["Setanta-sis!", "El setanta-sis!", "Setanta-sis!"],
  77: ["Setanta-set, doble set, doble sort!", "El setanta-set!", "Setanta-set!"],
  78: ["Setanta-vuit!", "El setanta-vuit!", "Setanta-vuit!"],
  79: ["Setanta-nou!", "El setanta-nou!", "Setanta-nou!"],
  80: ["Vuitanta, vuit desenes!", "El vuitanta!", "Vuitanta!"],
  81: ["Vuitanta-u!", "El vuitanta-u!", "Vuitanta-u!"],
  82: ["Vuitanta-dos!", "El vuitanta-dos!", "Vuitanta-dos!"],
  83: ["Vuitanta-tres!", "El vuitanta-tres!", "Vuitanta-tres!"],
  84: ["Vuitanta-quatre!", "El vuitanta-quatre!", "Vuitanta-quatre!"],
  85: ["Vuitanta-cinc!", "El vuitanta-cinc!", "Vuitanta-cinc!"],
  86: ["Vuitanta-sis!", "El vuitanta-sis!", "Vuitanta-sis!"],
  87: ["Vuitanta-set!", "El vuitanta-set!", "Vuitanta-set!"],
  88: ["Vuitanta-vuit, dues papallones!", "El vuitanta-vuit!", "Vuitanta-vuit, doble vuit!"],
  89: ["Vuitanta-nou, quasi l'últim!", "El vuitanta-nou!", "Vuitanta-nou!"],
  90: ["NORANTA! L'últim! La QUINA!", "NORANTA! Ja hem acabat! Visca!", "NORANTA! El gran final!"]
};
